[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[client]
showErrorDetails = true
showSidebarNavigation = true

[logger]
level = "info"

[client.toolbarMode]
toolbarMode = "minimal"
